"""One-way Git-object projection. Never merge runtime changes back into development."""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]


def sha(data):
    return hashlib.sha256(data).hexdigest()


def canonical(value):
    return (json.dumps(value, sort_keys=True, indent=2) + '\n').encode()


def git(*args):
    return subprocess.check_output(['git', '-C', str(ROOT), *args])


def promote(commit, reference, output, qualification=None):
    commit = git('rev-parse', commit + '^{commit}').decode().strip()
    if commit != git('rev-parse', 'HEAD').decode().strip() or git('status', '--porcelain').strip():
        raise ValueError('promotion requires the declared clean HEAD; commit source changes first')
    def blob(path):
        return git('show', f'{commit}:{path}')
    surface_bytes = blob('release/runtime-surface.json')
    surface = json.loads(surface_bytes)
    spec = surface['references'][reference]
    ref_bytes = blob(f'reference/{reference}/manifest.json')
    if sha(ref_bytes) != spec['sha256']:
        raise ValueError('Reference Release identity drift')
    ref = json.loads(ref_bytes)
    for name, digest in ref['files'].items():
        if sha(blob(f'reference/{reference}/{name}')) != digest:
            raise ValueError(f'Reference material drift: {name}')
    if sha(blob('ds41f_mlx/reference.py')) != ref['verifier_sha256']:
        raise ValueError('Reference verifier drift')
    contract_bytes = blob(f'reference/{reference}/contract.json')
    contract = json.loads(contract_bytes)
    lock = json.loads(blob('third_party/mtp/sources.json'))
    for dep in lock['sources'].values():
        if sha(blob('third_party/mtp/' + dep['archive'])) != dep['sha256']:
            raise ValueError('dependency source drift')
    entries, payload = {}, {}
    modes = {}
    for line in git('ls-tree', '-r', commit).decode().splitlines():
        meta, path = line.split('\t'); mode, kind, _ = meta.split()
        modes[path] = mode
    for dest, source in surface['files'].items():
        if source not in modes or modes[source] not in ('100644', '100755'):
            raise ValueError(f'missing/nonregular required source: {source}')
        if Path(dest).is_absolute() or '..' in Path(dest).parts:
            raise ValueError('unsafe release destination')
        data = blob(source)
        payload[dest] = data
        entries[dest] = dict(sha256=sha(data), size=len(data), mode=modes[source], origin=source)
    tree_identity = sha(canonical(entries))
    qualification_result = {'status': 'NOT_RELEASE_QUALIFIED'}
    receipt_path = 'release/promotion-qualification.json'
    if qualification or receipt_path in modes:
        if receipt_path not in modes:
            raise ValueError('qualification must be committed in the authoritative source')
        qbytes = blob(receipt_path)
        if qualification and Path(qualification).read_bytes() != qbytes:
            raise ValueError('qualification differs from authoritative committed receipt')
        q = json.loads(qbytes)
        ancestor = subprocess.run(['git', '-C', str(ROOT), 'merge-base', '--is-ancestor', q['source_commit'], commit]).returncode == 0
        if (q['status'] != 'PASS' or not ancestor or
                q['source_tree_sha256'] != tree_identity or q['reference_sha256'] != spec['sha256']):
            raise ValueError('qualification does not bind this promotion input')
        qualification_result = dict(receipt_sha256=sha(qbytes), **q)
    manifest = dict(schema='ds41f.promotion.v1', source_repository='ds41f-mlx', source_commit=commit,
        authority='official semantics > ds41f-mlx implementation/qualification > Reference Release > runtime projection',
        development_policy='Fix and qualify in ds41f-mlx; replace projection. Runtime-only patches are unsupported.',
        reference=dict(name=reference, sha256=spec['sha256']),
        semantic_contract=dict(schema=contract['schema'], sha256=sha(contract_bytes)),
        release_surface_sha256=sha(surface_bytes),
        promotion_implementation_sha256=sha(blob('tools/promote_release.py')),
        source_tree_sha256=tree_identity, files=entries,
        identity_rule='SHA256 canonical JSON files map; excludes only this derived promotion envelope. Compare envelope separately. No binaries generated by promotion.',
        nondeterministic_artifacts=surface['nondeterministic_artifacts'],
        dependencies=dict(sources=lock, requirements_sha256=sha(blob('third_party/mtp/requirements.lock')),
                          off_source_sha256=sha(blob(f'reference/{reference}/off-source.tar.gz'))),
        checkpoint_compatibility=contract['identities'], profiles=contract['profiles'],
        exclusions=[x for x in contract['exclusions'] if x != 'M43 extraction'],
        inherited_qualification=contract['inherited_evidence'],
        inherited_receipts={p:sha(blob(p)) for p in surface['inherited_receipts']},
        qualification=qualification_result)
    output = Path(output).resolve()
    if output == ROOT or output.is_relative_to(ROOT):
        raise ValueError('output must be independent of development checkout')
    if output.exists() and any(output.iterdir()):
        raise ValueError('output must be empty; never reconcile runtime edits')
    output.mkdir(parents=True, exist_ok=True)
    for dest, data in payload.items():
        p = output / dest; p.parent.mkdir(parents=True, exist_ok=True); p.write_bytes(data)
        p.chmod(0o755 if entries[dest]['mode'] == '100755' else 0o644)
    (output/'release/promotion.json').write_bytes(canonical(manifest))
    return manifest


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--source', default='HEAD')
    p.add_argument('--reference', required=True)
    p.add_argument('--output', type=Path, required=True)
    p.add_argument('--qualification', type=Path, help='must match the committed release/promotion-qualification.json; otherwise the committed receipt is used automatically, or a NOT_RELEASE_QUALIFIED candidate is created')
    a = p.parse_args()
    m = promote(a.source, a.reference, a.output, a.qualification)
    print(json.dumps({k:m[k] for k in ('source_commit','source_tree_sha256','qualification')}, indent=2))


if __name__ == '__main__':
    main()
