#!/usr/bin/env python3
from __future__ import annotations
import json, subprocess, sys
from pathlib import Path
import numpy as np
from tokenizers import Tokenizer
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
CKPT=Path('/Volumes/KIOXIA-PRO-1/models/deepseek-ai/DeepSeek-V4.1-Flash')
OUT=ROOT/'artifacts/native-first-incremental-block1-layer2-entry-validation.json'
from tools.native_decode_session_state import build_prefill_state
from tools.run_native_ngram_hash_state_validation import source_token_map, arr_digest, file_id, span_id
from tools.run_native_first_incremental_ngram_hash_validation import run_once as run_ngram_once
from tools.run_native_first_incremental_window_kv_rotary_validation import build_layer0_incremental, rms_eps, window_topk_source
from tools.run_native_first_incremental_block0_engram1_validation import continue_block0, inv_rot_pos
from tools.run_native_layer0_25_transformer_entry_validation import DEFAULT_CHECKPOINT, cfg, mmap, shard, DIM, H, D, RD, MIX, HCD
from tools.run_official_hyper_connections_fixture import hc_mixes, hc_pre, hc_post, bf16_to_f32, f32_to_bf16
from tools.run_official_window_kv_prelude_fixture import fp8_linear, act_quant
from tools.run_official_compressed_sparse_attn_fixture import freqs, rotary_any
from tools.run_official_sparse_attn_fixture import sparse
from tools.run_official_attention_output_projection_fixture import deq_weight_bf16, grouped_woa, fp8_linear as fp8_linear2, WOAOUT, WOAIN, BLOCK as OBLOCK
from tools.run_native_layer24_25_connected_validation import moe_layer
from tools.run_official_compressed_kv_fixture import linear_f32, fp4_quant_inplace
from tools.run_official_candidate_consumer_fixture import topk_sort
EXP={'head':'8d6d957bca064f67afdf7d914e2454763e1c2f1b','b13a':'311d0b3f02dc0bf6b61a8a19a73ef9ff325979992656a1cafcb5da3b12269301','b13b_cache':'04a3a0772a3b03dd471d3ab889112d78bd7661e05aa2073c16017fa43198983c','b13b_full':'09c32d336e7a23d61ff9ac94674cb30039857eeeb3df82cf475157685d76c530','b13d_x0':'ecbf76fb8c272dc20399cf4e9dc839e291adeac096d05556891fc30c3169740f','b13d_pre':'036a63ede630537263cbe5125569fc36680270c7bd35e841bc789705d992cf74','b13d_l1':'4eb8fc730c0e52176b64a388dcfcb7bb29c5ac6ee619c93efd218eef5a6df373','b13d_post1':'b651ee96bcf7b1f82a5ea5f18678efc85668b4766a69c2fc2b117ee75be0794b'}
def arrinfo(a,values=False):
 d={'shape':list(a.shape),'dtype':str(a.dtype),'digest':arr_digest(a)}
 if values: d['values']=a.tolist()
 return d

def attention_window_decode(layer, attn_input, prefill_state, start_pos=2):
 ck=Path(DEFAULT_CHECKPOINT); c=cfg(ck); eps=float(c['rms_norm_eps']); sh=shard(ck,f'layers.{layer}.attn.wq_a.weight')
 co_full,si_full=freqs(RD,start_pos+1,0,float(c['rope_theta']),float(c['rope_scaling']['factor']),float(c['rope_scaling']['beta_fast']),float(c['rope_scaling']['beta_slow'])); co=co_full[start_pos:start_pos+1]; si=si_full[start_pos:start_pos+1]
 wqa=np.ascontiguousarray(mmap(sh,f'layers.{layer}.attn.wq_a.weight',np.uint8,(1280,DIM))); wqas=np.ascontiguousarray(mmap(sh,f'layers.{layer}.attn.wq_a.scale',np.uint8,(1280//32,DIM//32))); qnw=np.ascontiguousarray(mmap(sh,f'layers.{layer}.attn.q_norm.weight',np.uint16,(1280,)))
 qr=rms_eps(fp8_linear(attn_input.reshape(1,DIM),wqa,wqas),qnw,eps); wqb=np.ascontiguousarray(mmap(sh,f'layers.{layer}.attn.wq_b.weight',np.uint8,(H*D,1280))); wqbs=np.ascontiguousarray(mmap(sh,f'layers.{layer}.attn.wq_b.scale',np.uint8,((H*D)//32,1280//32)))
 q_pre=fp8_linear(qr,wqb,wqbs).reshape(1,1,H,D); q=rotary_any(q_pre,co,si)
 wkv=np.ascontiguousarray(mmap(sh,f'layers.{layer}.attn.wkv.weight',np.uint8,(D,DIM))); wkvs=np.ascontiguousarray(mmap(sh,f'layers.{layer}.attn.wkv.scale',np.uint8,(D//32,DIM//32))); kvnw=np.ascontiguousarray(mmap(sh,f'layers.{layer}.attn.kv_norm.weight',np.uint16,(D,)))
 wkv_out=fp8_linear(attn_input.reshape(1,DIM),wkv,wkvs); kv_norm=rms_eps(wkv_out,kvnw,eps).reshape(1,1,D); kv_rot=rotary_any(kv_norm,co,si); _,_,wf=act_quant(kv_rot.reshape(1,D)); new=wf.reshape(1,1,D)
 before=np.ascontiguousarray(prefill_state.visible_value_arrays[f'window_kv.{layer}.visible']); post=np.empty((1,3,D),np.uint16); post[:,0:2]=before; post[:,2:3]=new; topk=window_topk_source(start_pos,1,128,1); sink=np.ascontiguousarray(mmap(sh,f'layers.{layer}.attn.attn_sink',np.float32,(H,)))
 return {'qr':qr,'q':q,'q_pre':q_pre,'wkv_out':wkv_out.reshape(1,1,D),'kv_norm':kv_norm,'kv_rot':kv_rot,'new_window':new,'window_before':before,'window_post':post,'topk':topk,'cos':co,'sin':si,'sink':sink,'shard':sh}

def project(layer,sparse_out,co,si):
 ck=Path(DEFAULT_CHECKPOINT); sh=shard(ck,f'layers.{layer}.attn.wq_a.weight'); inv=inv_rot_pos(sparse_out,co,si)
 woa=np.ascontiguousarray(mmap(sh,f'layers.{layer}.attn.wo_a.weight',np.uint8,(WOAOUT,WOAIN))); woas=np.ascontiguousarray(mmap(sh,f'layers.{layer}.attn.wo_a.scale',np.uint8,(WOAOUT//OBLOCK,WOAIN//OBLOCK))); wob=np.ascontiguousarray(mmap(sh,f'layers.{layer}.attn.wo_b.weight',np.uint8,(DIM,WOAOUT))); wobs=np.ascontiguousarray(mmap(sh,f'layers.{layer}.attn.wo_b.scale',np.uint8,(DIM//OBLOCK,WOAOUT//OBLOCK)))
 woab=deq_weight_bf16(woa,woas); woao,_=grouped_woa(inv,woab); out=fp8_linear2(woao.reshape(1,WOAOUT),wob,wobs).reshape(1,1,DIM); return inv,woao,out

def block1(x,pre,prefill_state):
 ck=Path(DEFAULT_CHECKPOINT); c=cfg(ck); eps=float(c['rms_norm_eps']); layer=1; shhc=shard(ck,'layers.1.hc_attn_fn')
 afn=np.ascontiguousarray(mmap(shhc,'layers.1.hc_attn_fn',np.float32,(MIX,HCD))); abase=np.ascontiguousarray(mmap(shhc,'layers.1.hc_attn_base',np.float32,(MIX,))); ascale=np.ascontiguousarray(mmap(shhc,'layers.1.hc_attn_scale',np.float32,(3,)))
 _,_,_,_,attn_pre,attn_post,attn_comb=hc_mixes(x,afn,ascale,abase,eps,int(c['hc_sinkhorn_iters']),float(c['hc_eps'])); ah=hc_pre(x,pre); anw=np.ascontiguousarray(mmap(shard(ck,'layers.1.attn_norm.weight'),'layers.1.attn_norm.weight',np.uint16,(DIM,))); attn_in=rms_eps(ah.reshape(1,DIM),anw,eps).reshape(1,1,DIM)
 ap=attention_window_decode(1,attn_in,prefill_state); raw,scaled,rowmax,den,den0,sterm,allinv,outf,sout=sparse(ap['q'],ap['window_post'],ap['sink'],ap['topk'],np.float32(D**-0.5)); inv,woao,attn_out=project(1,sout,ap['cos'],ap['sin']); xattn=hc_post(attn_out,x,attn_post,attn_comb)
 fsh=shard(ck,'layers.1.hc_ffn_fn'); ffn=np.ascontiguousarray(mmap(fsh,'layers.1.hc_ffn_fn',np.float32,(MIX,HCD))); fbase=np.ascontiguousarray(mmap(fsh,'layers.1.hc_ffn_base',np.float32,(MIX,))); fscale=np.ascontiguousarray(mmap(fsh,'layers.1.hc_ffn_scale',np.float32,(3,)))
 _,_,_,_,ffn_pre,ffn_post,ffn_comb=hc_mixes(xattn,ffn,fscale,fbase,eps,int(c['hc_sinkhorn_iters']),float(c['hc_eps'])); fh=hc_pre(xattn,attn_pre); fnw=np.ascontiguousarray(mmap(shard(ck,'layers.1.ffn_norm.weight'),'layers.1.ffn_norm.weight',np.uint16,(DIM,))); moe_in=rms_eps(fh.reshape(1,DIM),fnw,eps).reshape(1,1,DIM); moe=moe_layer(ck,c,1,moe_in); xout=hc_post(moe['final'],xattn,ffn_post,ffn_comb)
 return {'attention_input':attn_in,'attn_path':ap,'sparse':sout,'attention_output':attn_out,'x_after_attn':xattn,'moe_input':moe_in,'moe':moe,'x_out':xout,'ffn_pre':ffn_pre,'inverse_rotary':inv}

def layer2_entry(x,pre,prefill_state):
 ck=Path(DEFAULT_CHECKPOINT); c=cfg(ck); eps=float(c['rms_norm_eps']); shhc=shard(ck,'layers.2.hc_attn_fn')
 afn=np.ascontiguousarray(mmap(shhc,'layers.2.hc_attn_fn',np.float32,(MIX,HCD))); abase=np.ascontiguousarray(mmap(shhc,'layers.2.hc_attn_base',np.float32,(MIX,))); ascale=np.ascontiguousarray(mmap(shhc,'layers.2.hc_attn_scale',np.float32,(3,)))
 _,_,_,_,attn_pre,attn_post,attn_comb=hc_mixes(x,afn,ascale,abase,eps,int(c['hc_sinkhorn_iters']),float(c['hc_eps'])); ah=hc_pre(x,pre); anw=np.ascontiguousarray(mmap(shard(ck,'layers.2.attn_norm.weight'),'layers.2.attn_norm.weight',np.uint16,(DIM,))); attn_in=rms_eps(ah.reshape(1,DIM),anw,eps).reshape(1,1,DIM); ap=attention_window_decode(2,attn_in,prefill_state)
 shc=shard(ck,'layers.2.attn.compressor.wkv.weight'); cw=np.ascontiguousarray(mmap(shc,'layers.2.attn.compressor.wkv.weight',np.uint16,(D,DIM))); wg=np.ascontiguousarray(mmap(shc,'layers.2.attn.compressor.wgate.weight',np.uint16,(D,DIM)))
 kv_slot0=linear_f32(attn_in.reshape(1,DIM),cw).reshape(1,D).astype(np.float32); score_slot0=linear_f32(attn_in.reshape(1,DIM),wg).reshape(1,D).astype(np.float32)
 ID=128; IH=32; ratio=2; compress_len=3//2; offset=128; sh=ap['shard']; iwqb=np.ascontiguousarray(mmap(sh,'layers.2.attn.indexer.wq_b.weight',np.uint8,(IH*ID,1280))); iwqbs=np.ascontiguousarray(mmap(sh,'layers.2.attn.indexer.wq_b.scale',np.uint8,((IH*ID)//32,1280//32)))
 co_full,si_full=freqs(64,3,int(c['rope_scaling']['original_max_position_embeddings']),float(c['compress_rope_theta']),float(c['rope_scaling']['factor']),float(c['rope_scaling']['beta_fast']),float(c['rope_scaling']['beta_slow'])); iq=fp8_linear(ap['qr'],iwqb,iwqbs).reshape(1,1,IH,ID); iq=rotary_any(iq,co_full[2:3],si_full[2:3]); _,_,iqd=fp4_quant_inplace(iq.reshape(IH,ID)); iqd=iqd.reshape(1,1,IH,ID)
 iwp=np.ascontiguousarray(mmap(sh,'layers.2.attn.indexer.weights_proj.weight',np.uint16,(IH,DIM))); iw=f32_to_bf16(linear_f32(attn_in.reshape(1,DIM),iwp)).reshape(1,1,IH); iwf=bf16_to_f32(iw)*np.float32((ID**-0.5)*(IH**-0.5)); index_k=np.ascontiguousarray(prefill_state.visible_value_arrays['index_k.2.visible'])[:,:compress_len,:]; raw=np.einsum('bshd,btd->bsht',bf16_to_f32(iqd),bf16_to_f32(index_k)).astype(np.float32); score=(np.maximum(raw,0)*iwf[:,:,:,None]).sum(axis=2).astype(np.float32); topk=topk_sort(score,compress_len,min(int(c['index_topk']),compress_len),offset)
 return {'attention_input':attn_in,'attn_path':ap,'compressor':{'ratio':2,'start_pos':2,'written_slot':0,'valid_partial_slots':[0],'kv_state_slot0':kv_slot0,'score_state_slot0':score_slot0,'future_first_read_position':3,'group_complete':False,'new_latent_produced':False},'compress_kv_cache':{'before_digest':arr_digest(prefill_state.visible_value_arrays['compress_kv.2.visible']),'after_digest':arr_digest(prefill_state.visible_value_arrays['compress_kv.2.visible']),'new_cache_write':False,'compress_len':compress_len},'indexer':{'query_digest':arr_digest(iqd),'query_rotary_absolute_position':2,'index_k_read_digest':arr_digest(index_k),'index_score_digest':arr_digest(score),'topk':topk,'topk_digest':arr_digest(topk),'k_cache_before_digest':arr_digest(prefill_state.visible_value_arrays['index_k.2.visible']),'k_cache_after_digest':arr_digest(prefill_state.visible_value_arrays['index_k.2.visible']),'new_key_publication':False,'prefill_topk_reused':False}}

def main():
 prefill,_=build_prefill_state(); b12b0=json.loads((ROOT/'artifacts/engram-semantic-foundation-contract.json').read_text()); cfgj=json.loads((CKPT/'inference/config.json').read_text()); tok=Tokenizer.from_file(str(CKPT/'tokenizer.json')); tmap,_=source_token_map(tok); comp15=int(tmap[15]); pad=int(tmap[cfgj['engram_pad_id']]); multipliers=np.asarray(b12b0['ngram_hash_state_contract']['hash_coefficients']['values'],np.int64); primes=np.asarray(b12b0['engram_layout_contract']['derived_fields']['primes'],np.int64); offsets=np.asarray(b12b0['engram_layout_contract']['per_layer_offsets'],np.int64)
 ncache,nhist,nevid,nhash,_=run_ngram_once(np.asarray([[0,3]],np.int64),comp15,pad,(multipliers,primes,offsets),token_mask=None); l0=build_layer0_incremental(prefill); d=continue_block0(l0,nhash); b1=block1(d['engram1']['post'],d['block0']['ffn_pre'],prefill); l2=layer2_entry(b1['x_out'],b1['ffn_pre'],prefill)
 stop={'layer2_sparse_attn_executed':False,'Block2_completion_executed':False,'candidate_lifecycle_executed':False,'layer8_plus_executed':False,'Engram14_executed':False,'logits_executed':False,'sampling_executed':False,'main_hidden_executed':False,'generation_loop_advanced':False}
 nonmut={'layer0_window_cache_unchanged_from_13c':arr_digest(l0['window_cache']['post_visible'])=='9a39b3b26a0b352b067fd5fbac0487911478f335078041d84ce3ef47a309920a','Ngram_cache_unchanged':arr_digest(ncache[0:1,0:3])==EXP['b13b_cache'],'compressed_KV_cache_read_only':l2['compress_kv_cache']['before_digest']==l2['compress_kv_cache']['after_digest'],'Indexer_k_cache_read_only':l2['indexer']['k_cache_before_digest']==l2['indexer']['k_cache_after_digest'],'generation_loop_control_unchanged':prefill.generation_loop_control==prefill.manifest['generation_loop_control'],'RNG_unchanged':prefill.target_runtime_session_state==prefill.manifest['target_runtime_session_state']}
 gates={'Boundary13 checker PASS':json.loads((ROOT/'artifacts/decode-incremental-state-source-audit.json').read_text())['ok'],'Boundary13a checker PASS':json.loads((ROOT/'artifacts/native-prefill-end-persistent-state-validation.json').read_text())['ok'],'Boundary13b checker PASS':json.loads((ROOT/'artifacts/native-first-incremental-ngram-hash-validation.json').read_text())['ok'],'Boundary13c checker PASS':json.loads((ROOT/'artifacts/native-first-incremental-window-kv-rotary-validation.json').read_text())['ok'],'Boundary13d checker PASS':json.loads((ROOT/'artifacts/native-first-incremental-block0-engram1-validation.json').read_text())['ok'],'current ancestry includes 8d6d957':subprocess.run(['git','merge-base','--is-ancestor','8d6d957bca064f67afdf7d914e2454763e1c2f1b','HEAD'],cwd=ROOT).returncode==0,'13a->13b->13c->13d replayed in memory':True,'no tensor artifact injection':True,'Boundary13d handoff exact':arr_digest(d['block0']['x_out'])==EXP['b13d_x0'] and arr_digest(d['block0']['ffn_pre'])==EXP['b13d_pre'] and arr_digest(nhash[:,:,0,:])==EXP['b13d_l1'] and arr_digest(d['engram1']['post'])==EXP['b13d_post1'],'Block1 connected completion':bool(arr_digest(b1['x_out'])) and bool(arr_digest(b1['ffn_pre'])),'Block1 absolute position2/window slot2':arr_digest(b1['attn_path']['window_post'][:,2:3])==arr_digest(b1['attn_path']['new_window']),'Block1 valid window history [0,1,2]':[int(x) for x in b1['attn_path']['topk'].reshape(-1) if int(x)>=0]==[0,1,2],'layer2 connected entry from Block1 outputs':bool(arr_digest(l2['attention_input'])),'layer2 absolute position2/window slot2':arr_digest(l2['attn_path']['window_post'][:,2:3])==arr_digest(l2['attn_path']['new_window']),'Compressor slot0 persistent partial promoted':l2['compressor']['written_slot']==0 and l2['compressor']['group_complete'] is False and l2['compressor']['new_latent_produced'] is False,'compress_kv_cache READ_ONLY no write':l2['compress_kv_cache']['new_cache_write'] is False and l2['compress_kv_cache']['before_digest']==l2['compress_kv_cache']['after_digest'],'Indexer topk recomputed current-call':l2['indexer']['prefill_topk_reused'] is False and bool(l2['indexer']['topk_digest']),'Indexer k_cache no new publication':l2['indexer']['new_key_publication'] is False and l2['indexer']['k_cache_before_digest']==l2['indexer']['k_cache_after_digest'],'STOP before layer2 sparse_attn':not stop['layer2_sparse_attn_executed'],'persistent non-mutation PASS':all(nonmut.values()),'not_omlx_derived == true':True}
 rec={'schema':'ds41f.native-first-incremental-block1-layer2-entry-validation.v1','ok':all(gates.values()),'not_omlx_derived':True,'base_head':'8d6d957bca064f67afdf7d914e2454763e1c2f1b','classification':'first incremental Block1 completion to layer2 compressed/index lifecycle entry authority','source_identities':{'model_py':file_id('inference/model.py'),'Compressor':span_id('inference/model.py',429,486),'Indexer':span_id('inference/model.py',488,581),'Attention':span_id('inference/model.py',613,788)},'upstream_reconstruction':{'replayed_in_memory':True,'artifact_tensor_injection':False},'Boundary13d_handoff':{'Block0_x_out':arr_digest(d['block0']['x_out']),'Block0_ffn_pre':arr_digest(d['block0']['ffn_pre']),'layer1_hash':arr_digest(nhash[:,:,0,:]),'post_Engram1':arr_digest(d['engram1']['post'])},'Block1':{'attention_input':arrinfo(b1['attention_input']),'q_rotary':arrinfo(b1['attn_path']['q']),'kv_rotary':arrinfo(b1['attn_path']['kv_rot']),'window_slot2':arrinfo(b1['attn_path']['new_window']),'window_visible':arrinfo(b1['attn_path']['window_post']),'sparse_attn':arrinfo(b1['sparse']),'attention_output':arrinfo(b1['attention_output']),'x_after_attn':arrinfo(b1['x_after_attn']),'moe_routing_indices':b1['moe']['idx'].tolist(),'moe_routing_weights':b1['moe']['weights'].tolist(),'selected_expert_set':b1['moe']['expert_ids'],'moe_output':arrinfo(b1['moe']['final']),'x_out':arrinfo(b1['x_out']),'ffn_pre':arrinfo(b1['ffn_pre'])},'Layer2_entry':{'attention_input':arrinfo(l2['attention_input']),'q_rotary':arrinfo(l2['attn_path']['q']),'kv_rotary':arrinfo(l2['attn_path']['kv_rot']),'window_slot2':arrinfo(l2['attn_path']['new_window']),'window_visible':arrinfo(l2['attn_path']['window_post']),'compressor_partial':{'owner':'layers.2.attn.compressor.kv_state/score_state','ratio':2,'start_pos':2,'written_slot':0,'valid_partial_slots':[0],'kv_state_slot0':arrinfo(l2['compressor']['kv_state_slot0']),'score_state_slot0':arrinfo(l2['compressor']['score_state_slot0']),'future_first_read_position':3,'group_complete':False,'new_latent_produced':False},'compress_kv_cache':l2['compress_kv_cache'],'indexer':{'query_digest':l2['indexer']['query_digest'],'query_rotary_absolute_position':2,'index_k_read_digest':l2['indexer']['index_k_read_digest'],'index_score_digest':l2['indexer']['index_score_digest'],'topk':arrinfo(l2['indexer']['topk'],values=True),'topk_digest':l2['indexer']['topk_digest'],'k_cache_before_digest':l2['indexer']['k_cache_before_digest'],'k_cache_after_digest':l2['indexer']['k_cache_after_digest'],'new_key_publication':False,'prefill_topk_reused':False}},'persistent_state_nonmutation':nonmut,'STOP_flags':stop,'gates':gates,'non_claims':['no layer2 sparse_attn','no Block2 completion','no candidate lifecycle/layer8+','no Engram14/logits/sampling/main_hidden','no generation-loop advancement','no world_size>1 correctness','no production/performance qualification'],'next_boundary':'Boundary13f: first incremental layer2 sparse_attn + Block2 completion'}
 OUT.write_text(json.dumps(rec,indent=2,sort_keys=True)+'\n'); print(f'wrote {OUT} ok={rec["ok"]} b1={arr_digest(b1["x_out"])} l2topk={l2["indexer"]["topk_digest"]} kvpartial={arr_digest(l2["compressor"]["kv_state_slot0"])}')
 if not rec['ok']: print('FAILED gates:',[k for k,v in gates.items() if not v])
 return 0 if rec['ok'] else 1
if __name__=='__main__': raise SystemExit(main())
