#!/usr/bin/env python3
from __future__ import annotations
import argparse,json,os,sys,hashlib
from pathlib import Path
from typing import Any
import numpy as np
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
from ds41f_mlx.runtime.omlx_core import DEFAULT_CHECKPOINT, DEFAULT_OMLX, OmlxRuntime, OmlxRuntimeConfig
from ds41f_mlx.runtime.omlx_decode import OMLXDecodeConfig, OMLXDecodeSession
from tools.run_m4_omlx_base_decode_qualification import build_prefill_state
from tools.run_official_hyper_connections_fixture import bf16_to_f32

def sha(a): return hashlib.sha256(np.ascontiguousarray(a).view(np.uint8)).hexdigest()
def u16_from_mx_bf16(mx, a):
    mx.eval(a)
    try:
        return np.asarray(a.view(mx.uint16)).astype(np.uint16, copy=False)
    except Exception:
        # fallback through f32 is diagnostic only; exact bit gate will be false
        f=np.asarray(a.astype(mx.float32)).astype(np.float32)
        return f

def cmp_bf16(ref_u16, got_u16):
    ref=np.asarray(ref_u16)
    got=np.asarray(got_u16)
    exact = ref.dtype==np.uint16 and got.dtype==np.uint16 and ref.shape==got.shape and np.array_equal(ref,got)
    if ref.dtype==np.uint16 and got.dtype==np.uint16 and ref.shape==got.shape:
        d=np.abs(bf16_to_f32(ref)-bf16_to_f32(got)); max_abs=float(d.max()) if d.size else 0.0; mean_abs=float(d.mean()) if d.size else 0.0
    else:
        rf=bf16_to_f32(ref) if ref.dtype==np.uint16 else ref.astype(np.float32); gf=bf16_to_f32(got) if got.dtype==np.uint16 else got.astype(np.float32); d=np.abs(rf-gf); max_abs=float(d.max()) if d.size else None; mean_abs=float(d.mean()) if d.size else None
    return {'shape_pair':[list(ref.shape),list(got.shape)],'dtype_pair':[str(ref.dtype),str(got.dtype)],'reference_sha256':sha(ref),'actual_sha256':sha(got),'exact':bool(exact),'max_abs_diff':max_abs,'mean_abs_diff':mean_abs,'within_contract':bool(exact)}

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--checkpoint',default=os.environ.get('DS41F_CHECKPOINT',str(DEFAULT_CHECKPOINT))); ap.add_argument('--omlx-path',default=os.environ.get('DS41F_OMLX',str(DEFAULT_OMLX))); ap.add_argument('--out',default='artifacts/m4/admission-semantic-roundtrip/result.json'); a=ap.parse_args()
    ck=Path(a.checkpoint); omlx=Path(a.omlx_path)
    if str(omlx) not in sys.path: sys.path.insert(0,str(omlx))
    import mlx.core as mx
    from omlx.patches.deepseek_v41.quantization import unpack_activation
    rt=OmlxRuntime(OmlxRuntimeConfig(omlx_path=omlx,checkpoint_path=ck,engram_ssd_offload=True,preserve_mtp=False)); model,_=rt.load_model()
    try:
        prefill=build_prefill_state(ck,Path('artifacts/m4/admission-semantic-roundtrip/native'),[0,3],require_ok=True); st=prefill.continuation_state
        sess=OMLXDecodeSession.from_prefill_state(model,st,OMLXDecodeConfig(omlx_path=omlx,checkpoint_path=ck,preserve_mtp=False)); cache=sess.cache
        windows={}
        for l in range(40):
            sem=unpack_activation(cache[l].cache[1],bits=8,group_size=32,e4m3_scale=False,dtype=mx.bfloat16)
            got=u16_from_mx_bf16(mx,sem); windows[str(l)]=cmp_bf16(st.window_kv_by_layer[l],got)
        sources={}
        for s in [2,8,14,20]:
            sem2=unpack_activation(cache[s].cache[2],bits=4,group_size=16,e4m3_scale=True,dtype=mx.bfloat16)
            sem3=unpack_activation(cache[s].cache[3],bits=4,group_size=32,e4m3_scale=False,dtype=mx.bfloat16)
            sources[str(s)]={'compressed_kv':cmp_bf16(st.compressed_kv_by_source[s],u16_from_mx_bf16(mx,sem2)),'index_k':cmp_bf16(st.index_k_by_source[s],u16_from_mx_bf16(mx,sem3))}
        pending={}
        for s in [2,8,14,20]:
            p=st.compressor_pending.get(s,{})
            slot4=cache[s].cache[4]; slot5=cache[s].cache[5]
            pending[str(s)]={'committed_pending_keys':sorted(p.keys()),'slot4_shape':list(slot4.shape),'slot4_dtype':str(slot4.dtype),'slot5_shape':list(slot5.shape),'slot5_dtype':str(slot5.dtype),'empty_lifecycle_ok':not p and slot4.shape[1]==0 and slot5.shape[1]==0}
        # Engram history exactness: compare admitted slot6 to oMLX hasher regenerated from committed tokens and record official state hash digests.
        slot6=np.asarray(cache[0].cache[6]); lm=getattr(model,'language_model',model); _hashes,hist=lm._hasher(np.asarray(st.token_ids,dtype=np.int64),None,None)
        hist=np.asarray(hist,dtype=np.int64)
        engram={'slot6_shape':list(slot6.shape),'slot6_dtype':str(slot6.dtype),'expected_history_shape':list(hist.shape),'slot6_sha256':sha(slot6),'expected_history_sha256':sha(hist),'exact':bool(np.array_equal(slot6,hist)),'committed_ngram_hash_digests':{k:sha(v) for k,v in st.ngram_hashes.items()},'contract':'slot6 regenerated by oMLX NgramHash from committed token_ids; exact against independently regenerated oMLX history, with committed official hash digests recorded'}
        offsets=[int(c.size()) for c in cache]
        source_failures=[]
        for src,vals in sources.items():
            for field,cmp in vals.items():
                if not cmp['within_contract']:
                    source_failures.append({'source':int(src),'field':field,'max_abs_diff':cmp['max_abs_diff'],'mean_abs_diff':cmp['mean_abs_diff'],'classification':'ADMISSION REPRESENTATION DEFECT: semantic committed state is not idempotent across adapter pack/unpack under existing exact post-quantized BF16 cache contract'})
        rec={'schema':'ds41f.m4.admission-semantic-roundtrip.v1','checkpoint':str(ck),'omlx_path':str(omlx),'prefill_artifact_ok':prefill.ok,'windows':windows,'sources':sources,'pending':pending,'engram_history':engram,'offsets':offsets,'all_offsets_2':all(x==2 for x in offsets),'summary':{'window_ok':all(v['within_contract'] for v in windows.values()),'sources_ok':all(v['compressed_kv']['within_contract'] and v['index_k']['within_contract'] for v in sources.values()),'pending_ok':all(v['empty_lifecycle_ok'] for v in pending.values()),'engram_ok':engram['exact'],'source_failures':source_failures},'first_independent_correctness_frontier':source_failures[0] if source_failures else None,'ok':False}
        rec['ok']=bool(rec['summary']['window_ok'] and rec['summary']['sources_ok'] and rec['summary']['pending_ok'] and rec['summary']['engram_ok'] and rec['all_offsets_2'])
    finally:
        rt.close()
    out=Path(a.out); out.parent.mkdir(parents=True,exist_ok=True); out.write_text(json.dumps(rec,indent=2,sort_keys=True)+'\n'); print(out); print('ok',rec['ok'],rec['summary']); return 0 if rec['ok'] else 2
if __name__=='__main__': raise SystemExit(main())
