#!/usr/bin/env python3
from __future__ import annotations
import argparse,json,os,sys
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
from tools.run_official_hc_attention_subblock_fixture import DEFAULT_CHECKPOINT, mmap, shard, digest, hc_mixes, hc_pre, hc_post, attn_path, VOCAB, DIM, HC, MIX, HCD, rms
REF='artifacts/hc-attention-subblock-official-reference-fixture.json'
DS4_AUTHORITY_REMOTE='https://github.com/antirez/ds4.git'; DS4_AUTHORITY_SHA='0aaea5a238fb41a35106a551e73c8409dfb751ac'

def cmp(a,e,tol,floaty=False):
    aa=np.asarray(a); ee=np.asarray(e)
    if floaty:
        d=np.abs(aa.astype(np.float32)-ee.astype(np.float32)) if aa.shape==ee.shape else np.array([1e30],np.float32); m=float(d.max()) if d.size else 0.0
        return {'shape_matches':aa.shape==ee.shape,'max_abs_diff':m,'within_tolerance':aa.shape==ee.shape and m<=tol,'bit_exact':aa.shape==ee.shape and np.array_equal(aa,ee)}
    d=np.abs(aa.astype(np.int64)-ee.astype(np.int64)) if aa.shape==ee.shape else np.array([2**31]); m=int(d.max()) if d.size else 0
    return {'shape_matches':aa.shape==ee.shape,'max_abs_diff':m,'within_tolerance':aa.shape==ee.shape and m<=tol,'bit_exact':aa.shape==ee.shape and m==0}

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--checkpoint',default=os.environ.get('DS41F_CHECKPOINT',DEFAULT_CHECKPOINT)); ap.add_argument('--reference',default=REF); ap.add_argument('--out',default='artifacts/native-hc-attention-subblock-validation.json'); a=ap.parse_args(); ck=Path(a.checkpoint); ref=json.loads(Path(a.reference).read_text()); cfg=json.load(open(ck/'config.json'))['text_config']; exp=ref['expected']; tol=ref['operation_contract']['predeclared_tolerance']
    sh=shard(ck,'layers.24.hc_attn_fn'); fn=np.ascontiguousarray(mmap(sh,'layers.24.hc_attn_fn',np.float32,(MIX,HCD))); base=np.ascontiguousarray(mmap(sh,'layers.24.hc_attn_base',np.float32,(MIX,))); scale=np.ascontiguousarray(mmap(sh,'layers.24.hc_attn_scale',np.float32,(3,)))
    emb=np.ascontiguousarray(mmap(ck/'model-00002-of-00048.safetensors','embed.weight',np.uint16,(VOCAB,DIM))); x_hc=np.asarray(exp['x_hc_bf16_uint16'],np.uint16); external_x=emb[[0,3]].reshape(1,2,DIM).copy(); pm=np.asarray(exp['incoming_pre_mix_f32'],np.float32)
    flat,mean_sq,rsqrt,mixes,attn_pre,attn_post,attn_comb=hc_mixes(x_hc,fn,scale,base,float(cfg['rms_norm_eps']),int(cfg['hc_sinkhorn_iters']),float(cfg['hc_eps']))
    h_pre=hc_pre(x_hc,pm); attn_norm_w=np.ascontiguousarray(mmap(shard(ck,'layers.24.attn_norm.weight'),'layers.24.attn_norm.weight',np.uint16,(DIM,))); h_norm=rms(h_pre.reshape(2,DIM),attn_norm_w).reshape(1,2,DIM)
    apath=attn_path(ck,cfg,h_norm,external_x); x_after=hc_post(apath['attention_output'],x_hc,attn_post,attn_comb)
    comps={'incoming_pre_mix':cmp(pm,np.asarray(exp['incoming_pre_mix_f32'],np.float32),0,True),'attn_pre':cmp(attn_pre,np.asarray(exp['attn_pre_f32'],np.float32),tol['f32_max_abs_lte'],True),'attn_post':cmp(attn_post,np.asarray(exp['attn_post_f32'],np.float32),tol['f32_max_abs_lte'],True),'attn_comb':cmp(attn_comb,np.asarray(exp['attn_comb_f32'],np.float32),tol['f32_max_abs_lte'],True),'hc_pre_output':cmp(h_pre,np.asarray(exp['hc_pre_output_bf16_uint16'],np.uint16),tol['bf16_max_ulp_lte']),'attn_norm_output':cmp(h_norm,np.asarray(exp['attn_norm_output_bf16_uint16'],np.uint16),tol['bf16_max_ulp_lte']),'window_kv':cmp(apath['window_kv'],np.asarray(exp['window_kv_bf16_uint16'],np.uint16),tol['bf16_max_ulp_lte']),'compressed_topk_before':cmp(apath['compressed_topk_before'],np.asarray(exp['compressed_topk_before_offset_int32'],np.int32),0),'compressed_topk_after':cmp(apath['compressed_topk_after'],np.asarray(exp['compressed_topk_after_offset_int32'],np.int32),0),'assembled_kv':cmp(apath['concat_kv'],np.asarray(exp['assembled_kv_bf16_uint16'],np.uint16),tol['bf16_max_ulp_lte']),'assembled_topk':cmp(apath['concat_topk'],np.asarray(exp['assembled_topk_int32'],np.int32),0),'sparse_attn_output':cmp(apath['sparse_out'],np.asarray(exp['sparse_attn_output_bf16_uint16'],np.uint16),tol['bf16_max_ulp_lte']),'final_attention_output':cmp(apath['attention_output'],np.asarray(exp['final_attention_output_bf16_uint16'],np.uint16),tol['bf16_max_ulp_lte']),'hc_post_output':cmp(x_after,np.asarray(exp['hc_post_output_bf16_uint16'],np.uint16),tol['bf16_max_ulp_lte']),'returned_attn_pre':cmp(attn_pre,np.asarray(exp['returned_attn_pre_f32'],np.float32),0,True)}
    rec={'schema':'ds41f.native-hc-attention-subblock-validation.v1','classification':'official_reference_derived_native_validation','not_omlx_derived':True,'purpose':'validate Boundary 6b HC + Attention sub-block integration; stop before FFN/MoE','checkpoint':a.checkpoint,'authority':{'reference_fixture':a.reference,'official_checkpoint_raw_bits':a.checkpoint,'native_validation_provider':'single Python-orchestrated dataflow using validated Boundary 5/6a arithmetic primitives'},'reference_fixture':a.reference,'official_reference':ref['official_reference'],'operation_contract':ref['operation_contract'],'ds4_authority':{'remote':DS4_AUTHORITY_REMOTE,'commit':DS4_AUTHORITY_SHA},'comparison':comps,'digests':{'attention_input_sha256':digest(h_norm),'final_attention_output_sha256':digest(apath['attention_output']),'hc_post_output_sha256':digest(x_after)},'semantic_status':{'block_forward_attention_order_reviewed':True,'actual_attn_norm_hc_tensor_provenance_recorded':bool(ref.get('source_tensors')),'non_trivial_incoming_pre_mix_exercised':True,'hc_pre_validated':comps['hc_pre_output']['within_tolerance'],'attn_norm_validated':comps['attn_norm_output']['within_tolerance'],'attention_path_under_hc_input_validated':all(comps[k]['within_tolerance'] for k in ['window_kv','compressed_topk_after','assembled_kv','assembled_topk','sparse_attn_output']),'final_attention_output_validated':comps['final_attention_output']['within_tolerance'],'hc_post_validated':comps['hc_post_output']['within_tolerance'],'returned_attn_pre_exact':comps['returned_attn_pre']['bit_exact'],'ffn_entered':False,'model_semantics_validated':False},'non_claims':ref['non_claims']}
    rec['gates']={'block_forward_attention_order_reviewed':True,'actual_layer24_attn_norm_hc_tensor_provenance_recorded':rec['semantic_status']['actual_attn_norm_hc_tensor_provenance_recorded'],'non_trivial_incoming_pre_mix_exercised':True,'hc_pre_pass':rec['semantic_status']['hc_pre_validated'],'attn_norm_pass':rec['semantic_status']['attn_norm_validated'],'attention_path_pass_under_hc_input':rec['semantic_status']['attention_path_under_hc_input_validated'],'final_attention_output_pass':rec['semantic_status']['final_attention_output_validated'],'hc_post_pass':rec['semantic_status']['hc_post_validated'],'returned_attn_pre_exact':rec['semantic_status']['returned_attn_pre_exact'],'ffn_not_entered':not rec['semantic_status']['ffn_entered'],'full_model_semantics_not_claimed':not rec['semantic_status']['model_semantics_validated']}
    rec['ok']=all(rec['gates'].values())
    out=Path(a.out); out.parent.mkdir(parents=True,exist_ok=True); out.write_text(json.dumps(rec,indent=2,sort_keys=True)+'\n'); print(out); return 0 if rec['ok'] else 1
if __name__=='__main__': raise SystemExit(main())
