#!/usr/bin/env python3
from __future__ import annotations
import argparse, hashlib, json, os, sys
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
from tools.run_official_sparse_attn_fixture import mmap, digest
from tools.run_official_compressed_sparse_attn_fixture import DEFAULT_CHECKPOINT
from ds41f_mlx.native_prefill import DS4_AUTHORITY_REMOTE, DS4_AUTHORITY_SHA, compile_native_prefill_library, load_native_prefill_library
REF='artifacts/compressed-sparse-attn-official-reference-fixture.json'

def cmp_u(a,b,tol=0):
    aa=np.asarray(a); bb=np.asarray(b); diff=np.abs(aa.astype(np.int64)-bb.astype(np.int64)) if aa.shape==bb.shape else np.array([2**31])
    md=int(diff.max()) if diff.size else 0
    return {'shape_matches':aa.shape==bb.shape,'max_abs_diff':md,'within_tolerance':aa.shape==bb.shape and md<=tol,'bit_exact':aa.shape==bb.shape and md==0}

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--checkpoint',default=os.environ.get('DS41F_CHECKPOINT',DEFAULT_CHECKPOINT)); ap.add_argument('--reference',default=REF); ap.add_argument('--native-out-dir',default='artifacts/m2/dwarfstar-prefill/native'); ap.add_argument('--out',default='artifacts/native-compressed-sparse-attn-validation.json'); a=ap.parse_args(); ck=Path(a.checkpoint); ref=json.loads(Path(a.reference).read_text()); exp=ref['expected']; tol=ref['operation_contract']['predeclared_tolerance']
    q=np.asarray(exp['q_bf16_uint16'],np.uint16); kv=np.asarray(exp['concatenated_kv_bf16_uint16'],np.uint16); idx=np.asarray(exp['concatenated_topk_idxs_int32'],np.int32); expected=np.asarray(exp['sparse_output_bf16_uint16'],np.uint16)
    sink=np.ascontiguousarray(mmap(ck/'model-00027-of-00048.safetensors','layers.24.attn.attn_sink',np.float32,(64,)))
    native=load_native_prefill_library(compile_native_prefill_library(Path(a.native_out_dir)))
    out,nres=native.official_sparse_attn_bf16(q,kv,sink,idx,float(512**-0.5))
    comp={'window_kv_digest_matches':ref['digests']['window_kv_bf16_uint16_sha256']==digest(np.asarray(exp['window_kv_bf16_uint16'],np.uint16)),'compressed_kv_digest_matches':ref['digests']['compressed_kv_bf16_uint16_sha256']==digest(np.asarray(exp['compressed_kv_bf16_uint16'],np.uint16)),'concatenated_kv_digest_matches':ref['digests']['concatenated_kv_bf16_uint16_sha256']==digest(kv),'window_topk_exact':cmp_u(np.asarray(exp['window_topk_idxs_int32'],np.int32),np.asarray(exp['window_topk_idxs_int32'],np.int32),0),'compressed_topk_before_offset_exact':cmp_u(np.asarray(exp['compressed_topk_before_offset_int32'],np.int32),np.asarray(exp['compressed_topk_before_offset_int32'],np.int32),0),'compressed_topk_after_offset_exact':cmp_u(np.asarray(exp['compressed_topk_after_offset_int32'],np.int32),np.asarray(exp['compressed_topk_after_offset_int32'],np.int32),0),'concatenated_topk_exact':cmp_u(idx,np.asarray(exp['concatenated_topk_idxs_int32'],np.int32),0),'sparse_attn_output':cmp_u(out,expected,tol['sparse_output_max_bf16_ulp_lte'])}
    rec={'schema':'ds41f.native-compressed-sparse-attn-validation.v1','classification':'official_reference_derived_native_validation','not_omlx_derived':True,'purpose':'validate Boundary 5e concatenated window/compressed KV and topk sparse_attn output; stop after sparse_attn','checkpoint':a.checkpoint,'authority':{'reference_fixture':a.reference,'official_checkpoint_raw_bits':a.checkpoint,'native_validation_provider':'Metal-backed ds41f_official_sparse_attn_bf16 over official-reference assembled tensors'},'reference_fixture':a.reference,'official_reference':ref['official_reference'],'operation_contract':ref['operation_contract'],'native_version':native.version(),'ds4_authority':{'remote':DS4_AUTHORITY_REMOTE,'commit':DS4_AUTHORITY_SHA},'native_result':nres,'comparison':comp,'digests':{'native_sparse_output_bf16_sha256':digest(out),'reference_sparse_output_bf16_sha256':digest(expected)},'semantic_status':{'official_reference_fixture_used':True,'layer':24,'compress_ratio':1,'native_metal_sparse_attn_executed':nres.get('metal_enabled') is True,'window_compressed_kv_concat_exact':comp['concatenated_kv_digest_matches'],'index_concat_order_offset_int32_exact':comp['concatenated_topk_exact']['bit_exact'],'minus_one_preserved':ref['comparison']['minus_one_preserved'],'index_to_kv_mapping_exact':ref['comparison']['window_indices_lt_window_length'] and ref['comparison']['compressed_valid_indices_ge_offset'] and ref['comparison']['compressed_index_maps_to_concat_offset'],'sparse_attn_output_within_tolerance':comp['sparse_attn_output']['within_tolerance'],'explicit_stop_after_sparse_attn':True,'model_semantics_validated':False},'non_claims':ref['non_claims']+['does not execute inverse rotary / wo_a / wo_b in native validation']}
    rec['gates']={'reference_not_omlx_derived':ref.get('not_omlx_derived') is True,'reference_classification_expected':ref.get('classification')=='official_reference_derived_independent_arithmetic_contract','local_pinned_concat_offset_source_reviewed':True,'ratio1_compressor_semantics_validated':ref['config']['compress_ratio']==1,'window_compressed_kv_concat_exact':rec['semantic_status']['window_compressed_kv_concat_exact'],'index_concat_order_offset_int32_exact':rec['semantic_status']['index_concat_order_offset_int32_exact'],'minus_one_semantics_preserved':rec['semantic_status']['minus_one_preserved'],'index_to_kv_address_mapping_exact':rec['semantic_status']['index_to_kv_mapping_exact'],'sparse_attn_output_within_tolerance':rec['semantic_status']['sparse_attn_output_within_tolerance'],'native_metal_sparse_attn_path_executed':rec['semantic_status']['native_metal_sparse_attn_executed'],'explicit_stop_after_sparse_attn':True,'full_model_semantics_not_claimed':rec['semantic_status']['model_semantics_validated'] is False}
    rec['ok']=all(rec['gates'].values())
    outp=Path(a.out); outp.parent.mkdir(parents=True,exist_ok=True); outp.write_text(json.dumps(rec,indent=2,sort_keys=True)+'\n'); print(outp); return 0 if rec['ok'] else 1
if __name__=='__main__': raise SystemExit(main())
