#!/usr/bin/env python3
from __future__ import annotations
import argparse,json,os,sys
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
from tools.run_official_moe_shared_merge_fixture import DEFAULT_CHECKPOINT,shared_forward,digest,mmap,shard,DIM,INTER,BLOCK
from tools.run_official_moe_routed_reduction_fixture import build
from tools.run_official_moe_gate_expert_fixture import bf16_to_f32,f32_to_bf16
REF='artifacts/moe-shared-merge-official-reference-fixture.json'
DS4_AUTHORITY_REMOTE='https://github.com/antirez/ds4.git'; DS4_AUTHORITY_SHA='0aaea5a238fb41a35106a551e73c8409dfb751ac'
def cmp(a,e,tol,floaty=False):
 aa=np.asarray(a); ee=np.asarray(e)
 if floaty:
  d=np.abs(aa.astype(np.float32)-ee.astype(np.float32)) if aa.shape==ee.shape else np.array([1e30],np.float32); m=float(d.max()) if d.size else 0.0
  return {'shape_matches':aa.shape==ee.shape,'max_abs_diff':m,'within_tolerance':aa.shape==ee.shape and m<=tol,'bit_exact':aa.shape==ee.shape and np.array_equal(aa,ee)}
 d=np.abs(aa.astype(np.int64)-ee.astype(np.int64)) if aa.shape==ee.shape else np.array([2**31]); m=int(d.max()) if d.size else 0
 return {'shape_matches':aa.shape==ee.shape,'max_abs_diff':m,'within_tolerance':aa.shape==ee.shape and m<=tol,'bit_exact':aa.shape==ee.shape and m==0}
def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--checkpoint',default=os.environ.get('DS41F_CHECKPOINT',DEFAULT_CHECKPOINT)); ap.add_argument('--reference',default=REF); ap.add_argument('--out',default='artifacts/native-moe-shared-merge-validation.json'); a=ap.parse_args(); ck=Path(a.checkpoint); ref=json.loads(Path(a.reference).read_text()); exp=ref['expected']; tol=ref['operation_contract']['predeclared_tolerance']
 cfg,x,*rest=build(ck); routed=rest[11]
 sh=shard(ck,'layers.24.ffn.shared_experts.w1.weight'); p='layers.24.ffn.shared_experts'
 w1=np.ascontiguousarray(mmap(sh,p+'.w1.weight',np.uint8,(INTER,DIM))); s1=np.ascontiguousarray(mmap(sh,p+'.w1.scale',np.uint8,(INTER//BLOCK,DIM//BLOCK))); w2=np.ascontiguousarray(mmap(sh,p+'.w2.weight',np.uint8,(DIM,INTER))); s2=np.ascontiguousarray(mmap(sh,p+'.w2.scale',np.uint8,(DIM//BLOCK,INTER//BLOCK))); w3=np.ascontiguousarray(mmap(sh,p+'.w3.weight',np.uint8,(INTER,DIM))); s3=np.ascontiguousarray(mmap(sh,p+'.w3.scale',np.uint8,(INTER//BLOCK,DIM//BLOCK)))
 gate_b,up_b,gate_cl,up_cl,act,prod,prod_b,shared=shared_forward(x,w1,s1,w2,s2,w3,s3,cfg['swiglu_limit']); merge=(routed+bf16_to_f32(shared)).astype(np.float32); final=f32_to_bf16(merge).reshape(1,2,DIM)
 tiny_merge=(np.asarray(exp['tiny_routed_accumulator_f32'],np.float32)+bf16_to_f32(np.asarray(exp['tiny_shared_bf16_uint16'],np.uint16))).astype(np.float32); tiny_final=f32_to_bf16(tiny_merge)
 comps={'boundary6c1_routed_sum':cmp(routed,np.asarray(exp['boundary6c1_routed_sum_f32'],np.float32),tol['f32_max_abs_lte'],True),'shared_w1_projection':cmp(gate_b,np.asarray(exp['shared_w1_projection_bf16_uint16'],np.uint16),tol['bf16_max_ulp_lte']),'shared_w3_projection':cmp(up_b,np.asarray(exp['shared_w3_projection_bf16_uint16'],np.uint16),tol['bf16_max_ulp_lte']),'shared_activation_silu':cmp(act,np.asarray(exp['shared_activation_silu_f32'],np.float32),tol['f32_max_abs_lte'],True),'shared_gated_product':cmp(prod,np.asarray(exp['shared_gated_product_f32'],np.float32),tol['f32_max_abs_lte'],True),'shared_gated_product_bf16':cmp(prod_b,np.asarray(exp['shared_gated_product_bf16_uint16'],np.uint16),tol['bf16_max_ulp_lte']),'shared_expert_output':cmp(shared,np.asarray(exp['shared_expert_output_bf16_uint16'],np.uint16),tol['bf16_max_ulp_lte']),'merge_before_final_cast':cmp(merge,np.asarray(exp['merge_before_final_cast_f32'],np.float32),tol['f32_max_abs_lte'],True),'final_moe_output':cmp(final,np.asarray(exp['final_moe_output_bf16_uint16'],np.uint16),tol['bf16_max_ulp_lte']),'tiny_merge':cmp(tiny_merge,np.asarray(exp['tiny_merge_f32'],np.float32),0,True),'tiny_final':cmp(tiny_final,np.asarray(exp['tiny_final_bf16_uint16'],np.uint16),0)}
 rec={'schema':'ds41f.native-moe-shared-merge-validation.v1','classification':'official_reference_derived_native_validation','not_omlx_derived':True,'purpose':'validate Boundary 6c2 shared expert + routed/shared merge -> full MoE output; stop before FFN HC integration','checkpoint':a.checkpoint,'authority':{'reference_fixture':a.reference,'official_checkpoint_raw_bits':a.checkpoint,'native_validation_provider':'Python-orchestrated arithmetic over actual checkpoint tensors'},'reference_fixture':a.reference,'official_reference':ref['official_reference'],'operation_contract':ref['operation_contract'],'ds4_authority':{'remote':DS4_AUTHORITY_REMOTE,'commit':DS4_AUTHORITY_SHA},'comparison':comps,'digests':{'shared_expert_output_sha256':digest(shared),'reference_shared_expert_output_sha256':digest(np.asarray(exp['shared_expert_output_bf16_uint16'],np.uint16)),'final_moe_output_sha256':digest(final),'reference_final_moe_output_sha256':digest(np.asarray(exp['final_moe_output_bf16_uint16'],np.uint16))},'semantic_status':{'shared_expert_source_path_reviewed':True,'actual_shared_expert_tensor_provenance_recorded':bool(ref.get('source_tensors')),'shared_expert_primitive_validated':comps['shared_expert_output']['within_tolerance'],'boundary6c1_routed_sum_digest_verified':ref['comparison']['boundary6c1_routed_digest_verified'] and comps['boundary6c1_routed_sum']['within_tolerance'],'routed_shared_merge_dtype_order_validated':comps['merge_before_final_cast']['within_tolerance'],'independent_merge_fixture_validated':comps['tiny_merge']['within_tolerance'] and comps['tiny_final']['within_tolerance'],'final_moe_output_validated':comps['final_moe_output']['within_tolerance'],'model_semantics_validated':False},'non_claims':ref['non_claims']}
 rec['gates']={'shared_expert_source_path_reviewed':True,'actual_shared_expert_tensor_provenance_recorded':True,'shared_expert_primitive_pass':rec['semantic_status']['shared_expert_primitive_validated'],'boundary6c1_routed_sum_digest_verified':rec['semantic_status']['boundary6c1_routed_sum_digest_verified'],'merge_dtype_order_explicit':True,'independent_merge_fixture_pass':rec['semantic_status']['independent_merge_fixture_validated'],'final_moe_output_pass':rec['semantic_status']['final_moe_output_validated'],'full_model_semantics_not_claimed':not rec['semantic_status']['model_semantics_validated']}
 rec['ok']=all(rec['gates'].values()); out=Path(a.out); out.parent.mkdir(parents=True,exist_ok=True); out.write_text(json.dumps(rec,indent=2,sort_keys=True)+'\n'); print(out); return 0 if rec['ok'] else 1
if __name__=='__main__': raise SystemExit(main())
