#!/usr/bin/env python3
from __future__ import annotations
import argparse,json,os,sys
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
from tools.run_official_moe_gate_expert_fixture import DEFAULT_CHECKPOINT, mmap, shard, bf16_to_f32, f32_to_bf16, digest, fp4_linear, softplus_sqrt, silu, topk_desc, VOCAB, DIM, INTER, NEXP, TOPK, BLOCK
REF='artifacts/moe-gate-expert-official-reference-fixture.json'
DS4_AUTHORITY_REMOTE='https://github.com/antirez/ds4.git'; DS4_AUTHORITY_SHA='0aaea5a238fb41a35106a551e73c8409dfb751ac'
def cmp(a,e,tol,floaty=False):
 aa=np.asarray(a); ee=np.asarray(e)
 if floaty:
  d=np.abs(aa.astype(np.float32)-ee.astype(np.float32)) if aa.shape==ee.shape else np.array([1e30],np.float32); m=float(d.max()) if d.size else 0.0
  return {'shape_matches':aa.shape==ee.shape,'max_abs_diff':m,'within_tolerance':aa.shape==ee.shape and m<=tol,'bit_exact':aa.shape==ee.shape and np.array_equal(aa,ee)}
 d=np.abs(aa.astype(np.int64)-ee.astype(np.int64)) if aa.shape==ee.shape else np.array([2**31]); m=int(d.max()) if d.size else 0
 return {'shape_matches':aa.shape==ee.shape,'max_abs_diff':m,'within_tolerance':aa.shape==ee.shape and m<=tol,'bit_exact':aa.shape==ee.shape and m==0}
def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--checkpoint',default=os.environ.get('DS41F_CHECKPOINT',DEFAULT_CHECKPOINT)); ap.add_argument('--reference',default=REF); ap.add_argument('--out',default='artifacts/native-moe-gate-expert-validation.json'); a=ap.parse_args(); ck=Path(a.checkpoint); ref=json.loads(Path(a.reference).read_text()); cfg=json.load(open(ck/'config.json'))['text_config']; exp=ref['expected']; tol=ref['operation_contract']['predeclared_tolerance']
 sh=shard(ck,'layers.24.ffn.gate.weight'); x=np.asarray(exp['gate_input_bf16_uint16'],np.uint16); gw=np.ascontiguousarray(mmap(sh,'layers.24.ffn.gate.weight',np.uint16,(NEXP,DIM))); gb=np.ascontiguousarray(mmap(sh,'layers.24.ffn.gate.bias',np.float32,(NEXP,)))
 raw=(bf16_to_f32(x) @ bf16_to_f32(gw).T).astype(np.float32); scores=softplus_sqrt(raw); biased=(scores+gb).astype(np.float32); idx=topk_desc(biased,TOPK); selected=np.take_along_axis(scores,idx,axis=1); norm=(selected/(np.sum(selected,axis=1,keepdims=True,dtype=np.float32)+np.float32(1e-20))).astype(np.float32); weights=(norm*np.float32(cfg['routed_scaling_factor'])).astype(np.float32)
 expert_id=int(ref['inputs']['selected_expert_id']); prefix=f'layers.24.ffn.experts.{expert_id}'; w1=np.ascontiguousarray(mmap(sh,prefix+'.w1.weight',np.uint8,(INTER,DIM//2))); s1=np.ascontiguousarray(mmap(sh,prefix+'.w1.scale',np.uint8,(INTER,DIM//BLOCK))); w2=np.ascontiguousarray(mmap(sh,prefix+'.w2.weight',np.uint8,(DIM,INTER//2))); s2=np.ascontiguousarray(mmap(sh,prefix+'.w2.scale',np.uint8,(DIM,INTER//BLOCK))); w3=np.ascontiguousarray(mmap(sh,prefix+'.w3.weight',np.uint8,(INTER,DIM//2))); s3=np.ascontiguousarray(mmap(sh,prefix+'.w3.scale',np.uint8,(INTER,DIM//BLOCK)))
 ex_in=np.asarray(exp['expert_input_bf16_uint16'],np.uint16); gate=fp4_linear(ex_in,w1,s1,DIM); up=fp4_linear(ex_in,w3,s3,DIM); lim=np.float32(cfg['swiglu_limit']); up_cl=np.clip(up,-lim,lim).astype(np.float32); gate_cl=np.minimum(gate,lim).astype(np.float32); act=silu(gate_cl); prod=(act*up_cl).astype(np.float32); prod_bf16=f32_to_bf16(prod); final_f32=fp4_linear(prod_bf16,w2,s2,INTER); final=f32_to_bf16(final_f32)
 comps={'raw_gate_logits':cmp(raw,np.asarray(exp['raw_gate_logits_f32'],np.float32),tol['f32_max_abs_lte'],True),'score_transform':cmp(scores,np.asarray(exp['score_transform_f32'],np.float32),tol['f32_max_abs_lte'],True),'bias_applied_score':cmp(biased,np.asarray(exp['bias_applied_score_f32'],np.float32),tol['f32_max_abs_lte'],True),'topk_expert_indices':cmp(idx,np.asarray(exp['topk_expert_indices_int64'],np.int64),0),'selected_raw_scores':cmp(selected,np.asarray(exp['selected_raw_scores_f32'],np.float32),tol['f32_max_abs_lte'],True),'normalized_routing_weights':cmp(norm,np.asarray(exp['normalized_routing_weights_f32'],np.float32),tol['f32_max_abs_lte'],True),'scaled_routing_weights':cmp(weights,np.asarray(exp['scaled_routing_weights_f32'],np.float32),tol['f32_max_abs_lte'],True),'expert_w1_projection':cmp(gate,np.asarray(exp['expert_w1_projection_f32'],np.float32),tol['f32_max_abs_lte'],True),'expert_w3_projection':cmp(up,np.asarray(exp['expert_w3_projection_f32'],np.float32),tol['f32_max_abs_lte'],True),'expert_activation_silu':cmp(act,np.asarray(exp['expert_activation_silu_f32'],np.float32),tol['f32_max_abs_lte'],True),'expert_gated_product':cmp(prod,np.asarray(exp['expert_gated_product_f32'],np.float32),tol['f32_max_abs_lte'],True),'expert_gated_product_bf16':cmp(prod_bf16,np.asarray(exp['expert_gated_product_bf16_uint16'],np.uint16),tol['bf16_max_ulp_lte']),'expert_w2_projection':cmp(final_f32,np.asarray(exp['expert_w2_projection_f32'],np.float32),tol['f32_max_abs_lte'],True),'final_expert_output':cmp(final,np.asarray(exp['final_expert_output_bf16_uint16'],np.uint16),tol['bf16_max_ulp_lte'])}
 rec={'schema':'ds41f.native-moe-gate-expert-validation.v1','classification':'official_reference_derived_native_validation','not_omlx_derived':True,'purpose':'validate Boundary 6c0 MoE Gate routing + single routed Expert primitive; stop before reduction/shared experts','checkpoint':a.checkpoint,'authority':{'reference_fixture':a.reference,'official_checkpoint_raw_bits':a.checkpoint,'native_validation_provider':'Python-orchestrated arithmetic over actual checkpoint tensors; no new performance kernel'},'reference_fixture':a.reference,'official_reference':ref['official_reference'],'operation_contract':ref['operation_contract'],'ds4_authority':{'remote':DS4_AUTHORITY_REMOTE,'commit':DS4_AUTHORITY_SHA},'comparison':comps,'digests':{'final_expert_output_sha256':digest(final),'reference_final_expert_output_sha256':digest(np.asarray(exp['final_expert_output_bf16_uint16'],np.uint16))},'semantic_status':{'gate_expert_moe_source_reviewed':True,'actual_layer24_moe_config_recorded':True,'gate_tensor_provenance_recorded':True,'routing_indices_exact':comps['topk_expert_indices']['bit_exact'],'routing_weights_validated':comps['scaled_routing_weights']['within_tolerance'],'selected_expert_tensor_provenance_recorded':True,'expert_intermediates_validated':all(comps[k]['within_tolerance'] for k in ['expert_w1_projection','expert_w3_projection','expert_activation_silu','expert_gated_product','expert_w2_projection']),'final_single_expert_output_validated':comps['final_expert_output']['within_tolerance'],'routing_weight_applied_to_expert_output':False,'model_semantics_validated':False},'non_claims':ref['non_claims']}
 rec['gates']={'source_reviewed':True,'actual_layer24_moe_config_recorded':True,'gate_tensor_provenance_recorded':True,'routing_indices_exact':rec['semantic_status']['routing_indices_exact'],'routing_weights_validated':rec['semantic_status']['routing_weights_validated'],'selected_expert_tensor_provenance_recorded':True,'expert_intermediates_validated':rec['semantic_status']['expert_intermediates_validated'],'final_single_expert_output_validated':rec['semantic_status']['final_single_expert_output_validated'],'routing_weight_not_applied':not rec['semantic_status']['routing_weight_applied_to_expert_output'],'full_model_semantics_not_claimed':not rec['semantic_status']['model_semantics_validated']}
 rec['ok']=all(rec['gates'].values()); out=Path(a.out); out.parent.mkdir(parents=True,exist_ok=True); out.write_text(json.dumps(rec,indent=2,sort_keys=True)+'\n'); print(out); return 0 if rec['ok'] else 1
if __name__=='__main__': raise SystemExit(main())
